In [1]:
import preprocessing as pre
import pandas as pd
import numpy as np
import glob
import seaborn as sn
import matplotlib.pyplot as plt

%matplotlib inline

In [2]:
pwd

'C:\\Users\\ANAGHA SREE'

In [3]:
df_eeg = pre.process_all_excel_files()
df_eeg

      electrode brain_oscillation fft_abs_power    freq_band  id
0           FP1             Delta     15.376173    1.0-4.0Hz  01
1           FP2             Delta     16.585338    1.0-4.0Hz  01
2            F7             Delta      7.968847    1.0-4.0Hz  01
3            F3             Delta      9.749313    1.0-4.0Hz  01
4            Fz             Delta     10.845292    1.0-4.0Hz  01
...         ...               ...           ...          ...  ..
21104        Pz             Beta2      2.539991  15.0-18.0Hz  99
21105        P4             Beta2      2.364752  15.0-18.0Hz  99
21106        T6             Beta2      4.515852  15.0-18.0Hz  99
21107        O1             Beta2      2.281860  15.0-18.0Hz  99
21108        O2             Beta2      2.229536  15.0-18.0Hz  99

[21109 rows x 5 columns]

In [4]:
df_eeg = df_eeg[['id', 'brain_oscillation','freq_band','electrode','fft_abs_power']]

In [27]:
df_eeg = df_eeg[(df_eeg.id != '10') & (df_eeg.id != '18') & (df_eeg.id != '52') & (df_eeg.id != '215') & (df_eeg.id != '617')]

In [28]:
print(df_eeg.shape)
df_eeg.head(5)

(21109, 5)

   id brain_oscillation  freq_band electrode fft_abs_power
0   1             Delta  1.0-4.0Hz       FP1     15.376173
1   1             Delta  1.0-4.0Hz       FP2     16.585338
2   1             Delta  1.0-4.0Hz        F7      7.968847
3   1             Delta  1.0-4.0Hz        F3      9.749313
4   1             Delta  1.0-4.0Hz        Fz     10.845292

In [29]:
df_eeg.dtypes

id                    int32
brain_oscillation    object
freq_band            object
electrode            object
fft_abs_power        object
dtype: object

In [30]:
print(df_eeg.electrode.value_counts())
print(df_eeg.brain_oscillation.value_counts())
print(df_eeg.freq_band.value_counts())

electrode
FP1    1111
C4     1111
O1     1111
T6     1111
P4     1111
Pz     1111
P3     1111
T5     1111
T4     1111
Cz     1111
FP2    1111
C3     1111
T3     1111
F8     1111
F4     1111
Fz     1111
F3     1111
F7     1111
O2     1111
Name: count, dtype: int64
brain_oscillation
Delta        1919
Theta        1919
Alpha        1919
Beta         1919
HighBeta     1919
Gamma        1919
HighGamma    1919
Alpha1       1919
Alpha2       1919
Beta1        1919
Beta2        1919
Name: count, dtype: int64
freq_band
1.0-4.0Hz      1919
4.0-8.0Hz      1919
8.0-12.0Hz     1919
12.0-25.0Hz    1919
25.0-30.0Hz    1919
30.0-40.0Hz    1919
40.0-50.0Hz    1919
8.0-10.0Hz     1919
10.0-12.0Hz    1919
12.0-15.0Hz    1919
15.0-18.0Hz    1919
Name: count, dtype: int64

In [31]:
df_neuropsy = pd.read_excel("Neuropsy.xlsx", na_values=".")
print(df_neuropsy.shape)
df_neuropsy.head(5)

(100, 15)

,ID,Age,Gender,cIM,cHR,cIE,cSC,inat,hyper,Aqtot,Aqaudi,Aqvis,RCQtot,RCQaudi,RCQvis
0,1,21,1,17.0,31.0,29.0,9.0,18.0,20.0,90.0,91.0,92.0,94.0,80.0,110.0
1,3,20,1,10.0,5.0,13.0,1.0,8.0,5.0,27.0,34.0,41.0,25.0,31.0,38.0
2,4,18,1,26.0,17.0,7.0,15.0,23.0,11.0,93.0,89.0,96.0,90.0,92.0,90.0
3,7,23,1,24.0,8.0,6.0,14.0,19.0,3.0,86.0,66.0,112.0,94.0,90.0,100.0
4,10,18,1,NaN,NaN,NaN,NaN,NaN,NaN,98.0,103.0,93.0,92.0,100.0,85.0

In [32]:
df_neuropsy= df_neuropsy.dropna(axis=0, how='any')

In [33]:
print(df_neuropsy.shape)

(96, 15)

In [34]:
df_neuropsy.rename(columns = {'ID':'id'}, inplace = True) #rename id so it can be merged
df_neuropsy.head(5)

,id,Age,Gender,cIM,cHR,cIE,cSC,inat,hyper,Aqtot,Aqaudi,Aqvis,RCQtot,RCQaudi,RCQvis
0,1,21,1,17.0,31.0,29.0,9.0,18.0,20.0,90.0,91.0,92.0,94.0,80.0,110.0
1,3,20,1,10.0,5.0,13.0,1.0,8.0,5.0,27.0,34.0,41.0,25.0,31.0,38.0
2,4,18,1,26.0,17.0,7.0,15.0,23.0,11.0,93.0,89.0,96.0,90.0,92.0,90.0
3,7,23,1,24.0,8.0,6.0,14.0,19.0,3.0,86.0,66.0,112.0,94.0,90.0,100.0
5,11,21,1,16.0,26.0,13.0,10.0,17.0,13.0,45.0,33.0,78.0,69.0,51.0,94.0

In [35]:
df_eeg['id']=df_eeg['id'].astype(int)

In [36]:
df_neuropsy.rename(columns = {'ID':'id'}, inplace = True) #rename id so it can be merged
df_neuropsy.head(5)

,id,Age,Gender,cIM,cHR,cIE,cSC,inat,hyper,Aqtot,Aqaudi,Aqvis,RCQtot,RCQaudi,RCQvis
0,1,21,1,17.0,31.0,29.0,9.0,18.0,20.0,90.0,91.0,92.0,94.0,80.0,110.0
1,3,20,1,10.0,5.0,13.0,1.0,8.0,5.0,27.0,34.0,41.0,25.0,31.0,38.0
2,4,18,1,26.0,17.0,7.0,15.0,23.0,11.0,93.0,89.0,96.0,90.0,92.0,90.0
3,7,23,1,24.0,8.0,6.0,14.0,19.0,3.0,86.0,66.0,112.0,94.0,90.0,100.0
5,11,21,1,16.0,26.0,13.0,10.0,17.0,13.0,45.0,33.0,78.0,69.0,51.0,94.0

In [37]:
df_eeg['id']=df_eeg['id'].astype(int)

In [38]:
df_full = pd.merge(left=df_eeg, right=df_neuropsy, left_on='id', right_on='id')
df_full.head()

,id,brain_oscillation,freq_band,electrode,fft_abs_power,Age,Gender,cIM,cHR,cIE,cSC,inat,hyper,Aqtot,Aqaudi,Aqvis,RCQtot,RCQaudi,RCQvis
0,1,Delta,1.0-4.0Hz,FP1,15.376173,21,1,17.0,31.0,29.0,9.0,18.0,20.0,90.0,91.0,92.0,94.0,80.0,110.0
1,1,Delta,1.0-4.0Hz,FP2,16.585338,21,1,17.0,31.0,29.0,9.0,18.0,20.0,90.0,91.0,92.0,94.0,80.0,110.0
2,1,Delta,1.0-4.0Hz,F7,7.968847,21,1,17.0,31.0,29.0,9.0,18.0,20.0,90.0,91.0,92.0,94.0,80.0,110.0
3,1,Delta,1.0-4.0Hz,F3,9.749313,21,1,17.0,31.0,29.0,9.0,18.0,20.0,90.0,91.0,92.0,94.0,80.0,110.0
4,1,Delta,1.0-4.0Hz,Fz,10.845292,21,1,17.0,31.0,29.0,9.0,18.0,20.0,90.0,91.0,92.0,94.0,80.0,110.0

In [39]:
df_full = df_full.sort_values(by=['id'])

In [40]:
df_full['subtype'] = df_full.apply(lambda x: pre.categorize_subtypes(x['inat'], x['hyper']), axis=1)

df_full.head(5)

,id,brain_oscillation,freq_band,electrode,fft_abs_power,Age,Gender,cIM,cHR,cIE,cSC,inat,hyper,Aqtot,Aqaudi,Aqvis,RCQtot,RCQaudi,RCQvis,subtype
0,1,Delta,1.0-4.0Hz,FP1,15.376173,21,1,17.0,31.0,29.0,9.0,18.0,20.0,90.0,91.0,92.0,94.0,80.0,110.0,mixed
133,1,Alpha1,8.0-10.0Hz,FP1,2.416282,21,1,17.0,31.0,29.0,9.0,18.0,20.0,90.0,91.0,92.0,94.0,80.0,110.0,mixed
134,1,Alpha1,8.0-10.0Hz,FP2,2.287391,21,1,17.0,31.0,29.0,9.0,18.0,20.0,90.0,91.0,92.0,94.0,80.0,110.0,mixed
135,1,Alpha1,8.0-10.0Hz,F7,1.274912,21,1,17.0,31.0,29.0,9.0,18.0,20.0,90.0,91.0,92.0,94.0,80.0,110.0,mixed
136,1,Alpha1,8.0-10.0Hz,F3,2.218398,21,1,17.0,31.0,29.0,9.0,18.0,20.0,90.0,91.0,92.0,94.0,80.0,110.0,mixed

In [41]:
from sklearn.preprocessing import LabelEncoder

lb_make = LabelEncoder()
df_full["adhdtype"] = lb_make.fit_transform(df_full["subtype"])
df_full[["subtype", "adhdtype"]].head(11)

    subtype  adhdtype
0     mixed         2
133   mixed         2
134   mixed         2
135   mixed         2
136   mixed         2
137   mixed         2
138   mixed         2
139   mixed         2
140   mixed         2
141   mixed         2
142   mixed         2

In [42]:
df_full = df_full[['id','Age', 'Gender','inat','hyper',"subtype",'adhdtype', 'brain_oscillation','electrode','fft_abs_power', 'cIM', 'cHR', 'cIE', 'cSC', 'Aqtot', 'Aqaudi', 'Aqvis', 'RCQtot', 'RCQaudi', 'RCQvis']]
df_full.head()
df_full['adhdtype'].value_counts()

adhdtype
1    10032
2     9614
0      418
Name: count, dtype: int64

In [43]:
df_full.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20064 entries, 0 to 16092
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 20064 non-null  int32
 1   Age                20064 non-null  int64
 2   Gender             20064 non-null  int64
 3   inat               20064 non-null  float64
 4   hyper              20064 non-null  float64
 5   subtype            20064 non-null  object
 6   adhdtype           20064 non-null  int32
 7   brain_oscillation  20064 non-null  object
 8   electrode          20064 non-null  object
 9   fft_abs_power      20064 non-null  object
 10  cIM                20064 non-null  float64
 11  cHR                20064 non-null  float64
 12  cIE                20064 non-null  float64
 13  cSC                20064 non-null  float64
 14  Aqtot              20064 non-null  float64
 15  Aqaudi             20064 non-null  float64
 16  Aqvis              20064 non-null  float64
 17  RCQtot             20064 non-null  float64
 18  RCQaudi            20064 non-null  float64
 19  RCQvis             20064 non-null  float64
dtypes: float64(12), int32(2), int64(2), object(4)
memory usage: 3.1+ MB

In [44]:
df_full['fft_abs_power'] = df_full['fft_abs_power'].astype(float)
print(df_full.dtypes)

id                     int32
Age                    int64
Gender                 int64
inat                 float64
hyper                float64
subtype               object
adhdtype               int32
brain_oscillation     object
electrode             object
fft_abs_power        float64
cIM                  float64
cHR                  float64
cIE                  float64
cSC                  float64
Aqtot                float64
Aqaudi               float64
Aqvis                float64
RCQtot               float64
RCQaudi              float64
RCQvis               float64
dtype: object

In [45]:
df_full_eeg = df_full[['id', 'Gender', 'adhdtype','brain_oscillation','electrode', 'fft_abs_power']]
df_full_eeg

        id  Gender  adhdtype brain_oscillation electrode  fft_abs_power
0        1       1         2             Delta       FP1      15.376173
133      1       1         2            Alpha1       FP1       2.416282
134      1       1         2            Alpha1       FP2       2.287391
135      1       1         2            Alpha1        F7       1.274912
136      1       1         2            Alpha1        F3       2.218398
...    ...     ...       ...               ...       ...            ...
15958  702       1         1              Beta        O1      17.656688
15959  702       1         1              Beta        O2      16.284646
15960  702       1         1          HighBeta       FP1       1.127291
15935  702       1         1             Alpha        P3      26.927847
16092  702       1         1             Beta2        O2       3.086436

[20064 rows x 6 columns]

In [46]:
df_analysis = df_full[['id','Gender','subtype','adhdtype','brain_oscillation', 'electrode', 'fft_abs_power', 'cIM', 'cHR', 'cIE', 'cSC', 'Aqtot', 'Aqaudi', 'Aqvis', 'RCQtot', 'RCQaudi', 'RCQvis']]
print(df_analysis.head())

     id  Gender subtype  adhdtype brain_oscillation electrode  fft_abs_power  \
0     1       1   mixed         2             Delta       FP1      15.376173
133   1       1   mixed         2            Alpha1       FP1       2.416282
134   1       1   mixed         2            Alpha1       FP2       2.287391
135   1       1   mixed         2            Alpha1        F7       1.274912
136   1       1   mixed         2            Alpha1        F3       2.218398

      cIM   cHR   cIE  cSC  Aqtot  Aqaudi  Aqvis  RCQtot  RCQaudi  RCQvis
0    17.0  31.0  29.0  9.0   90.0    91.0   92.0    94.0     80.0   110.0
133  17.0  31.0  29.0  9.0   90.0    91.0   92.0    94.0     80.0   110.0
134  17.0  31.0  29.0  9.0   90.0    91.0   92.0    94.0     80.0   110.0
135  17.0  31.0  29.0  9.0   90.0    91.0   92.0    94.0     80.0   110.0
136  17.0  31.0  29.0  9.0   90.0    91.0   92.0    94.0     80.0   110.0

In [47]:
df_analysis.groupby(['Gender','subtype', 'brain_oscillation']).describe()

                                     id                                      \
                                  count        mean         std   min   25%
Gender subtype brain_oscillation
1      inat    Alpha              646.0  179.764706  185.621020   4.0  64.0
               Alpha1             646.0  179.764706  185.621020   4.0  64.0
               Alpha2             646.0  179.764706  185.621020   4.0  64.0
               Beta               646.0  179.764706  185.621020   4.0  64.0
               Beta1              646.0  179.764706  185.621020   4.0  64.0
               Beta2              646.0  179.764706  185.621020   4.0  64.0
               Delta              646.0  179.764706  185.621020   4.0  64.0
               Gamma              646.0  179.764706  185.621020   4.0  64.0
               HighBeta           646.0  179.764706  185.621020   4.0  64.0
               HighGamma          646.0  179.764706  185.621020   4.0  64.0
               Theta              646.0  179.764706  185.621020   4.0  64.0
       mixed   Alpha              437.0  154.869565  189.447661   1.0  14.0
               Alpha1             437.0  154.869565  189.447661   1.0  14.0
               Alpha2             437.0  154.869565  189.447661   1.0  14.0
               Beta               437.0  154.869565  189.447661   1.0  14.0
               Beta1              437.0  154.869565  189.447661   1.0  14.0
               Beta2              437.0  154.869565  189.447661   1.0  14.0
               Delta              437.0  154.869565  189.447661   1.0  14.0
               Gamma              437.0  154.869565  189.447661   1.0  14.0
               HighBeta           437.0  154.869565  189.447661   1.0  14.0
               HighGamma          437.0  154.869565  189.447661   1.0  14.0
               Theta              437.0  154.869565  189.447661   1.0  14.0
2      hyper   Alpha               38.0   77.500000   18.748333  59.0  59.0
               Alpha1              38.0   77.500000   18.748333  59.0  59.0
               Alpha2              38.0   77.500000   18.748333  59.0  59.0
               Beta                38.0   77.500000   18.748333  59.0  59.0
               Beta1               38.0   77.500000   18.748333  59.0  59.0
               Beta2               38.0   77.500000   18.748333  59.0  59.0
               Delta               38.0   77.500000   18.748333  59.0  59.0
               Gamma               38.0   77.500000   18.748333  59.0  59.0
               HighBeta            38.0   77.500000   18.748333  59.0  59.0
               HighGamma           38.0   77.500000   18.748333  59.0  59.0
               Theta               38.0   77.500000   18.748333  59.0  59.0
       inat    Alpha              266.0  108.000000  126.600486  19.0  24.0
               Alpha1             266.0  108.000000  126.600486  19.0  24.0
               Alpha2             266.0  108.000000  126.600486  19.0  24.0
               Beta               266.0  108.000000  126.600486  19.0  24.0
               Beta1              266.0  108.000000  126.600486  19.0  24.0
               Beta2              266.0  108.000000  126.600486  19.0  24.0
               Delta              266.0  108.000000  126.600486  19.0  24.0
               Gamma              266.0  108.000000  126.600486  19.0  24.0
               HighBeta           266.0  108.000000  126.600486  19.0  24.0
               HighGamma          266.0  108.000000  126.600486  19.0  24.0
               Theta              266.0  108.000000  126.600486  19.0  24.0
       mixed   Alpha              437.0  179.695652  174.422287  17.0  45.0
               Alpha1             437.0  179.695652  174.422287  17.0  45.0
               Alpha2             437.0  179.695652  174.422287  17.0  45.0
               Beta               437.0  179.695652  174.422287  17.0  45.0
               Beta1              437.0  179.695652  174.422287  17.0  45.0
               Beta2              437.0  179.695652  174.422287  17.0  45.0
               Delta              437.0  179.695652  174.422287  17.0  45.0
               Gamma              437.0  179.695652  174.422287  17.0  45.0
               HighBeta           437.0  179.695652  174.422287  17.0  45.0
               HighGamma          437.0  179.695652  174.422287  17.0  45.0
               Theta              437.0  179.695652  174.422287  17.0  45.0

                                                      adhdtype       ...  \
                                    50%    75%    max    count mean  ...
Gender subtype brain_oscillation                                     ...
1      inat    Alpha               84.0  220.0  702.0    646.0  1.0  ...
               Alpha1              84.0  220.0  702.0    646.0  1.0  ...
               Alpha2              84.0  220.0  702.0    646.0  1.0  ...
               Beta                84.0  220.0  702.0    646.0  1.0  ...
               Beta1               84.0  220.0  702.0    646.0  1.0  ...
               Beta2               84.0  220.0  702.0    646.0  1.0  ...
               Delta               84.0  220.0  702.0    646.0  1.0  ...
               Gamma               84.0  220.0  702.0    646.0  1.0  ...
               HighBeta            84.0  220.0  702.0    646.0  1.0  ...
               HighGamma           84.0  220.0  702.0    646.0  1.0  ...
               Theta               84.0  220.0  702.0    646.0  1.0  ...
       mixed   Alpha               80.0  213.0  701.0    437.0  2.0  ...
               Alpha1              80.0  213.0  701.0    437.0  2.0  ...
               Alpha2              80.0  213.0  701.0    437.0  2.0  ...
               Beta                80.0  213.0  701.0    437.0  2.0  ...
               Beta1               80.0  213.0  701.0    437.0  2.0  ...
               Beta2               80.0  213.0  701.0    437.0  2.0  ...
               Delta               80.0  213.0  701.0    437.0  2.0  ...
               Gamma               80.0  213.0  701.0    437.0  2.0  ...
               HighBeta            80.0  213.0  701.0    437.0  2.0  ...
               HighGamma           80.0  213.0  701.0    437.0  2.0  ...
               Theta               80.0  213.0  701.0    437.0  2.0  ...
2      hyper   Alpha               77.5   96.0   96.0     38.0  0.0  ...
               Alpha1              77.5   96.0   96.0     38.0  0.0  ...
               Alpha2              77.5   96.0   96.0     38.0  0.0  ...
               Beta                77.5   96.0   96.0     38.0  0.0  ...
               Beta1               77.5   96.0   96.0     38.0  0.0  ...
               Beta2               77.5   96.0   96.0     38.0  0.0  ...
               Delta               77.5   96.0   96.0     38.0  0.0  ...
               Gamma               77.5   96.0   96.0     38.0  0.0  ...
               HighBeta            77.5   96.0   96.0     38.0  0.0  ...
               HighGamma           77.5   96.0   96.0     38.0  0.0  ...
               Theta               77.5   96.0   96.0     38.0  0.0  ...
       inat    Alpha               61.5  121.0  409.0    266.0  1.0  ...
               Alpha1              61.5  121.0  409.0    266.0  1.0  ...
               Alpha2              61.5  121.0  409.0    266.0  1.0  ...
               Beta                61.5  121.0  409.0    266.0  1.0  ...
               Beta1               61.5  121.0  409.0    266.0  1.0  ...
               Beta2               61.5  121.0  409.0    266.0  1.0  ...
               Delta               61.5  121.0  409.0    266.0  1.0  ...
               Gamma               61.5  121.0  409.0    266.0  1.0  ...
               HighBeta            61.5  121.0  409.0    266.0  1.0  ...
               HighGamma           61.5  121.0  409.0    266.0  1.0  ...
               Theta               61.5  121.0  409.0    266.0  1.0  ...
       mixed   Alpha              126.0  216.0  700.0    437.0  2.0  ...
               Alpha1             126.0  216.0  700.0    437.0  2.0  ...
               Alpha2             126.0  216.0  700.0    437.0  2.0  ...
               Beta               126.0  216.0  700.0    437.0  2.0  ...
               Beta1              126.0  216.0  700.0    437.0  2.0  ...
               Beta2              126.0  216.0  700.0    437.0  2.0  ...
               Delta              126.0  216.0  700.0    437.0  2.0  ...
               Gamma              126.0  216.0  700.0    437.0  2.0  ...
               HighBeta           126.0  216.0  700.0    437.0  2.0  ...
               HighGamma          126.0  216.0  700.0    437.0  2.0  ...
               Theta              126.0  216.0  700.0    437.0  2.0  ...

                                 RCQaudi        RCQvis                        \
                                     75%    max  count       mean        std
Gender subtype brain_oscillation
1      inat    Alpha                94.0  113.0  646.0  76.558824  24.811515
               Alpha1               94.0  113.0  646.0  76.558824  24.811515
               Alpha2               94.0  113.0  646.0  76.558824  24.811515
               Beta                 94.0  113.0  646.0  76.558824  24.811515
               Beta1                94.0  113.0  646.0  76.558824  24.811515
               Beta2                94.0  113.0  646.0  76.558824  24.811515
               Delta                94.0  113.0  646.0  76.558824  24.811515
               Gamma                94.0  113.0  646.0  76.558824  24.811515
               HighBeta             94.0  113.0  646.0  76.558824  24.811515
               HighGamma            94.0  113.0  646.0  76.558824  24.811515
               Theta                94.0  113.0  646.0  76.558824  24.811515
       mixed   Alpha                85.0  122.0  437.0  71.739130  23.135335
               Alpha1               85.0  122.0  437.0  71.739130  23.135335
               Alpha2               85.0  122.0  437.0  71.739130  23.135335
               Beta                 85.0  122.0  437.0  71.739130  23.135335
               Beta1                85.0  122.0  437.0  71.739130  23.135335
               Beta2                85.0  122.0  437.0  71.739130  23.135335
               Delta                85.0  122.0  437.0  71.739130  23.135335
               Gamma                85.0  122.0  437.0  71.739130  23.135335
               HighBeta             85.0  122.0  437.0  71.739130  23.135335
               HighGamma            85.0  122.0  437.0  71.739130  23.135335
               Theta                85.0  122.0  437.0  71.739130  23.135335
2      hyper   Alpha               106.0  106.0   38.0  85.000000  12.161081
               Alpha1              106.0  106.0   38.0  85.000000  12.161081
               Alpha2              106.0  106.0   38.0  85.000000  12.161081
               Beta                106.0  106.0   38.0  85.000000  12.161081
               Beta1               106.0  106.0   38.0  85.000000  12.161081
               Beta2               106.0  106.0   38.0  85.000000  12.161081
               Delta               106.0  106.0   38.0  85.000000  12.161081
               Gamma               106.0  106.0   38.0  85.000000  12.161081
               HighBeta            106.0  106.0   38.0  85.000000  12.161081
               HighGamma           106.0  106.0   38.0  85.000000  12.161081
               Theta               106.0  106.0   38.0  85.000000  12.161081
       inat    Alpha                84.0  106.0  266.0  65.642857  27.949353
               Alpha1               84.0  106.0  266.0  65.642857  27.949353
               Alpha2               84.0  106.0  266.0  65.642857  27.949353
               Beta                 84.0  106.0  266.0  65.642857  27.949353
               Beta1                84.0  106.0  266.0  65.642857  27.949353
               Beta2                84.0  106.0  266.0  65.642857  27.949353
               Delta                84.0  106.0  266.0  65.642857  27.949353
               Gamma                84.0  106.0  266.0  65.642857  27.949353
               HighBeta             84.0  106.0  266.0  65.642857  27.949353
               HighGamma            84.0  106.0  266.0  65.642857  27.949353
               Theta                84.0  106.0  266.0  65.642857  27.949353
       mixed   Alpha               100.0  132.0  437.0  75.000000  22.396039
               Alpha1              100.0  132.0  437.0  75.000000  22.396039
               Alpha2              100.0  132.0  437.0  75.000000  22.396039
               Beta                100.0  132.0  437.0  75.000000  22.396039
               Beta1               100.0  132.0  437.0  75.000000  22.396039
               Beta2               100.0  132.0  437.0  75.000000  22.396039
               Delta               100.0  132.0  437.0  75.000000  22.396039
               Gamma               100.0  132.0  437.0  75.000000  22.396039
               HighBeta            100.0  132.0  437.0  75.000000  22.396039
               HighGamma           100.0  132.0  437.0  75.000000  22.396039
               Theta               100.0  132.0  437.0  75.000000  22.396039


                                   min   25%   50%   75%    max
Gender subtype brain_oscillation
1      inat    Alpha              37.0  55.0  76.5  97.0  122.0
               Alpha1             37.0  55.0  76.5  97.0  122.0
               Alpha2             37.0  55.0  76.5  97.0  122.0
               Beta               37.0  55.0  76.5  97.0  122.0
               Beta1              37.0  55.0  76.5  97.0  122.0
               Beta2              37.0  55.0  76.5  97.0  122.0
               Delta              37.0  55.0  76.5  97.0  122.0
               Gamma              37.0  55.0  76.5  97.0  122.0
               HighBeta           37.0  55.0  76.5  97.0  122.0
               HighGamma          37.0  55.0  76.5  97.0  122.0
               Theta              37.0  55.0  76.5  97.0  122.0
       mixed   Alpha              33.0  57.0  65.0  94.0  122.0
               Alpha1             33.0  57.0  65.0  94.0  122.0
               Alpha2             33.0  57.0  65.0  94.0  122.0
               Beta               33.0  57.0  65.0  94.0  122.0
               Beta1              33.0  57.0  65.0  94.0  122.0
               Beta2              33.0  57.0  65.0  94.0  122.0
               Delta              33.0  57.0  65.0  94.0  122.0
               Gamma              33.0  57.0  65.0  94.0  122.0
               HighBeta           33.0  57.0  65.0  94.0  122.0
               HighGamma          33.0  57.0  65.0  94.0  122.0
               Theta              33.0  57.0  65.0  94.0  122.0
2      hyper   Alpha              73.0  73.0  85.0  97.0   97.0
               Alpha1             73.0  73.0  85.0  97.0   97.0
               Alpha2             73.0  73.0  85.0  97.0   97.0
               Beta               73.0  73.0  85.0  97.0   97.0
               Beta1              73.0  73.0  85.0  97.0   97.0
               Beta2              73.0  73.0  85.0  97.0   97.0
               Delta              73.0  73.0  85.0  97.0   97.0
               Gamma              73.0  73.0  85.0  97.0   97.0
               HighBeta           73.0  73.0  85.0  97.0   97.0
               HighGamma          73.0  73.0  85.0  97.0   97.0
               Theta              73.0  73.0  85.0  97.0   97.0
       inat    Alpha               8.0  55.0  67.0  83.0  107.0
               Alpha1              8.0  55.0  67.0  83.0  107.0
               Alpha2              8.0  55.0  67.0  83.0  107.0
               Beta                8.0  55.0  67.0  83.0  107.0
               Beta1               8.0  55.0  67.0  83.0  107.0
               Beta2               8.0  55.0  67.0  83.0  107.0
               Delta               8.0  55.0  67.0  83.0  107.0
               Gamma               8.0  55.0  67.0  83.0  107.0
               HighBeta            8.0  55.0  67.0  83.0  107.0
               HighGamma           8.0  55.0  67.0  83.0  107.0
               Theta               8.0  55.0  67.0  83.0  107.0
       mixed   Alpha              26.0  55.0  75.0  94.0  111.0
               Alpha1             26.0  55.0  75.0  94.0  111.0
               Alpha2             26.0  55.0  75.0  94.0  111.0
               Beta               26.0  55.0  75.0  94.0  111.0
               Beta1              26.0  55.0  75.0  94.0  111.0
               Beta2              26.0  55.0  75.0  94.0  111.0
               Delta              26.0  55.0  75.0  94.0  111.0
               Gamma              26.0  55.0  75.0  94.0  111.0
               HighBeta           26.0  55.0  75.0  94.0  111.0
               HighGamma          26.0  55.0  75.0  94.0  111.0
               Theta              26.0  55.0  75.0  94.0  111.0

[55 rows x 104 columns]

In [48]:
df_connors = df_analysis[['id','Gender','cIM', 'cHR', 'cIE', 'cSC']]
df_behavioral = df_analysis[['id','Gender', 'Aqtot', 'Aqaudi', 'Aqvis', 'RCQtot', 'RCQaudi', 'RCQvis']]
df_labels = df_analysis[['id','adhdtype']]

df_labels

        id  adhdtype
0        1         2
133      1         2
134      1         2
135      1         2
136      1         2
...    ...       ...
15958  702         1
15959  702         1
15960  702         1
15935  702         1
16092  702         1

[20064 rows x 2 columns]

In [49]:
df_connors.to_csv('Data/df_connors')
df_behavioral.to_csv('Data/df_behavioral')
df_labels.to_csv('Data/labels')
df_full_eeg.to_csv('Data/df_eeg')
df_analysis = df_full[['id','Gender','subtype','adhdtype','brain_oscillation', 'electrode', 'fft_abs_power', 'cIM', 'cHR', 'cIE', 'cSC', 'Aqtot', 'Aqaudi', 'Aqvis', 'RCQtot', 'RCQaudi', 'RCQvis']]
print(df_analysis.head())
df_analysis.to_csv('Data/df_analysis')

     id  Gender subtype  adhdtype brain_oscillation electrode  fft_abs_power  \
0     1       1   mixed         2             Delta       FP1      15.376173
133   1       1   mixed         2            Alpha1       FP1       2.416282
134   1       1   mixed         2            Alpha1       FP2       2.287391
135   1       1   mixed         2            Alpha1        F7       1.274912
136   1       1   mixed         2            Alpha1        F3       2.218398

      cIM   cHR   cIE  cSC  Aqtot  Aqaudi  Aqvis  RCQtot  RCQaudi  RCQvis
0    17.0  31.0  29.0  9.0   90.0    91.0   92.0    94.0     80.0   110.0
133  17.0  31.0  29.0  9.0   90.0    91.0   92.0    94.0     80.0   110.0
134  17.0  31.0  29.0  9.0   90.0    91.0   92.0    94.0     80.0   110.0
135  17.0  31.0  29.0  9.0   90.0    91.0   92.0    94.0     80.0   110.0
136  17.0  31.0  29.0  9.0   90.0    91.0   92.0    94.0     80.0   110.0